/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const binancePlex = localFont({
  src: [
    {
      path: "../font/BinancePlex-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../font/BinancePlex-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../font/BinancePlex-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-binance-plex",
});

const binanceNova = localFont({
  src: [
    {
      path: "../font/BinanceNova-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../font/BinanceNova-Medium.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-binance-nova",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${binanceNova.className} ${binanceNova.variable}`}>
        {children}
      </body>
    </html>
  );
}
